area:desktop:
  - changed-files:
      - any-glob-to-any-file:
          - "apps/desktop/**"

area:controller:
  - changed-files:
      - any-glob-to-any-file:
          - "services/controller/**"

area:helper:
  - changed-files:
      - any-glob-to-any-file:
          - "services/priv-helper/**"

area:ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - ".github/*.md"
          - "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"
          - "**/requirements*.txt"
          - "**/Cargo.toml"
          - "**/Cargo.lock"
          - ".github/dependabot.yml"

