# Generated by Django 4.1 on 2023-06-20 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('course_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('hash_value', models.CharField(max_length=64, unique=True)),
                ('certificate_hash', models.CharField(max_length=64, null=True)),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(editable=False, max_length=64)),
                ('certificate_hash', models.CharField(max_length=64, null=True)),
                ('output_file', models.FilePathField(null=True, path='/u01/workspace/APP/blockchain_ar/blockchain_certificates/media')),
                ('certificate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate')),
            ],
        ),
    ]
