# Generated by Django 4.1 on 2023-06-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
