# Generated by Django 4.1 on 2024-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_rename_created_by_id_certificate_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='output_file',
            field=models.FilePathField(null=True, path='/u01/workspace/ai_apps/blockchain_certificates/media'),
        ),
    ]
