# Generated by Django 4.1 on 2024-05-26 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0004_certificate_arabicfamilyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='arabicFamilyName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='arabicFatherName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='arabicFirstName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='arabicGrandFatherName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='arabicName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='arabicNationality',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cardIssueDateGregorian',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cardIssueDateHijri',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='dobHijri',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='englishFamilyName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='englishFatherName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='englishFirstName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='englishGrandFatherName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='englishName',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='iam_login',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='idExpiryDateGregorian',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='idExpiryDateHijri',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='idVersionNo',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='iqamaExpiryDateGregorian',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='iqamaExpiryDateHijri',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issueLocationAr',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issueLocationEn',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='nationalityCode',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='preferredLang',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='sessionIndex',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='userid',
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionIndex', models.CharField(max_length=256)),
                ('userid', models.CharField(max_length=100)),
                ('arabicName', models.CharField(max_length=100)),
                ('arabicFirstName', models.CharField(max_length=100)),
                ('arabicFatherName', models.CharField(max_length=100)),
                ('arabicGrandFatherName', models.CharField(max_length=100)),
                ('arabicFamilyName', models.CharField(max_length=100)),
                ('englishName', models.CharField(max_length=100)),
                ('englishFirstName', models.CharField(max_length=100)),
                ('englishFatherName', models.CharField(max_length=100)),
                ('englishGrandFatherName', models.CharField(max_length=100)),
                ('englishFamilyName', models.CharField(max_length=100)),
                ('nationalityCode', models.CharField(max_length=50)),
                ('arabicNationality', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('dobHijri', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('lang', models.CharField(max_length=50)),
                ('preferredLang', models.CharField(max_length=50)),
                ('idVersionNo', models.CharField(max_length=50)),
                ('idExpiryDateHijri', models.DateField()),
                ('idExpiryDateGregorian', models.DateField()),
                ('iqamaExpiryDateHijri', models.DateField()),
                ('iqamaExpiryDateGregorian', models.DateField()),
                ('cardIssueDateHijri', models.DateField()),
                ('cardIssueDateGregorian', models.DateField()),
                ('issueLocationAr', models.CharField(max_length=100)),
                ('issueLocationEn', models.CharField(max_length=100)),
                ('iam_login', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
