# Generated by Django 4.1 on 2024-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_remove_certificate_arabicfamilyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='unique_id',
            field=models.CharField(default='default_unique_id', max_length=100, unique=True),
        ),
    ]
