# Generated by Django 4.1 on 2024-05-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_userdetails_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='unique_id',
        ),
    ]
