# Generated by Django 4.1 on 2025-02-24 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0007_remove_userdetails_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم الصلاحية بالعربي')),
                ('name_en', models.CharField(max_length=50, verbose_name='اسم الصلاحية بالإنجليزي')),
                ('can_view_templates', models.BooleanField(default=False, verbose_name='عرض القوالب')),
                ('can_create_templates', models.BooleanField(default=False, verbose_name='إنشاء القوالب')),
                ('can_edit_templates', models.BooleanField(default=False, verbose_name='تعديل القوالب')),
                ('can_delete_templates', models.BooleanField(default=False, verbose_name='حذف القوالب')),
                ('can_view_certificates', models.BooleanField(default=True, verbose_name='عرض الشهادات')),
                ('can_create_certificates', models.BooleanField(default=False, verbose_name='إنشاء الشهادات')),
                ('can_verify_certificates', models.BooleanField(default=True, verbose_name='التحقق من الشهادات')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='عرض المستخدمين')),
                ('can_create_users', models.BooleanField(default=False, verbose_name='إنشاء المستخدمين')),
                ('can_edit_users', models.BooleanField(default=False, verbose_name='تعديل المستخدمين')),
                ('can_delete_users', models.BooleanField(default=False, verbose_name='حذف المستخدمين')),
                ('can_view_roles', models.BooleanField(default=False, verbose_name='عرض الصلاحيات')),
                ('can_create_roles', models.BooleanField(default=False, verbose_name='إنشاء الصلاحيات')),
                ('can_edit_roles', models.BooleanField(default=False, verbose_name='تعديل الصلاحيات')),
                ('can_delete_roles', models.BooleanField(default=False, verbose_name='حذف الصلاحيات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='output_file',
            field=models.FilePathField(null=True, path='/u01/workspace/ai_apps/blockchain_certificates_v2/media'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pdf_file', models.FileField(upload_to='pdf_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('font_name', models.CharField(max_length=100)),
                ('font_color', models.CharField(max_length=20)),
                ('name_x', models.FloatField()),
                ('name_y', models.FloatField()),
                ('name_font_size', models.FloatField()),
                ('course_x', models.FloatField()),
                ('course_y', models.FloatField()),
                ('course_font_size', models.FloatField()),
                ('date_x', models.FloatField()),
                ('date_y', models.FloatField()),
                ('date_font_size', models.FloatField()),
                ('qr_x', models.FloatField()),
                ('qr_y', models.FloatField()),
                ('qr_size', models.FloatField()),
                ('qr_rotation', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
        ),
    ]
