# Generated by Django 4.1 on 2025-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_role_alter_block_output_file_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='output_file',
            field=models.FilePathField(null=True, path='/u01/workspace/ai_apps/blockchain_certificates/media'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
