# Generated by Django 4.1 on 2025-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0009_alter_block_output_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
