# Generated by Django 4.1 on 2025-09-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_alter_certificatetemplate_name'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - removes the column
            "ALTER TABLE certificates_certificatetemplate DROP COLUMN text_alignment_method;",
            # Reverse SQL - adds the column back (for rollback)
            "ALTER TABLE certificates_certificatetemplate ADD COLUMN text_alignment_method VARCHAR(50) DEFAULT 'left';"
        ),
    ]