# Generated by Django 4.1 on 2025-09-03 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_auto_20250902_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_temporary_role',
            field=models.BooleanField(default=False, verbose_name='صلاحية مؤقتة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='previous_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_profiles', to='certificates.role', verbose_name='الصلاحية السابقة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ نهاية الصلاحية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بداية الصلاحية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_organization',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم جهة المشرف'),
        ),
    ]
