# Generated by Django 4.1 on 2025-11-19 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0012_userprofile_is_temporary_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_advanced_certificates',
            field=models.BooleanField(default=False, verbose_name='إنشاء الشهادات المتقدمة'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_advanced_templates',
            field=models.BooleanField(default=False, verbose_name='إنشاء القوالب المتقدمة'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_advanced_templates',
            field=models.BooleanField(default=False, verbose_name='حذف القوالب المتقدمة'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_advanced_templates',
            field=models.BooleanField(default=False, verbose_name='تعديل القوالب المتقدمة'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_advanced_certificates',
            field=models.BooleanField(default=False, verbose_name='عرض الشهادات المتقدمة'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_advanced_templates',
            field=models.BooleanField(default=False, verbose_name='عرض القوالب المتقدمة'),
        ),
        migrations.CreateModel(
            name='AdvancedCertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القالب')),
                ('pdf_file', models.FileField(upload_to='advanced_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='ملف القالب')),
                ('certificate_type', models.CharField(choices=[('arabic', 'عربي - RTL'), ('english', 'إنجليزي - LTR'), ('bilingual', 'ثنائي اللغة (عربي + إنجليزي)')], default='bilingual', max_length=20, verbose_name='نوع الشهادة')),
                ('active_fields', models.JSONField(default=dict, verbose_name='الحقول النشطة')),
                ('field_settings', models.JSONField(default=dict, verbose_name='إعدادات الحقول')),
                ('qr_settings', models.JSONField(default=dict, verbose_name='إعدادات QR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_templates', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'قالب شهادة متقدم',
                'verbose_name_plural': 'قوالب الشهادات المتقدمة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='قيمة الهاش')),
                ('certificate_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='هاش الشهادة')),
                ('certificate_data', models.JSONField(verbose_name='بيانات الشهادة')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='البريد الإلكتروني')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advanced_certificates', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.advancedcertificatetemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'شهادة متقدمة',
                'verbose_name_plural': 'الشهادات المتقدمة',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='advancedcertificate',
            index=models.Index(fields=['certificate_hash'], name='certificate_certifi_a18bff_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedcertificate',
            index=models.Index(fields=['created_by', '-date'], name='certificate_created_2f0eb9_idx'),
        ),
    ]
