# Generated by Django 4.1 on 2025-11-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_rename_advanced_role'),
        ('certificates', '0013_role_can_create_advanced_certificates_and_more'),
    ]

    operations = [
    ]
