# Generated by Django 4.1 on 2026-01-21 13:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0014_merge_20251123_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedcertificate',
            options={'ordering': ['-date'], 'verbose_name': 'Advanced certificate', 'verbose_name_plural': 'Advanced certificates'},
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_transcript_templates',
            field=models.BooleanField(default=False, verbose_name='إنشاء قوالب السجلات'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_create_transcripts',
            field=models.BooleanField(default=False, verbose_name='إنشاء السجلات'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_delete_transcript_templates',
            field=models.BooleanField(default=False, verbose_name='حذف قوالب السجلات'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_transcript_templates',
            field=models.BooleanField(default=False, verbose_name='تعديل قوالب السجلات'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_transcript_templates',
            field=models.BooleanField(default=False, verbose_name='عرض قوالب السجلات'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_transcripts',
            field=models.BooleanField(default=False, verbose_name='عرض السجلات'),
        ),
        migrations.AlterField(
            model_name='advancedcertificatetemplate',
            name='certificate_type',
            field=models.CharField(choices=[('arabic', 'عربي'), ('english', 'إنجليزي'), ('bilingual', 'ثنائي اللغة (عربي + إنجليزي)')], default='bilingual', max_length=20, verbose_name='نوع الشهادة'),
        ),
        migrations.CreateModel(
            name='TranscriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القالب')),
                ('pdf_file', models.FileField(upload_to='transcript_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='ملف القالب')),
                ('transcript_type', models.CharField(choices=[('arabic', 'عربي'), ('english', 'إنجليزي'), ('bilingual', 'ثنائي اللغة (عربي + إنجليزي)')], default='bilingual', max_length=20, verbose_name='نوع السجل')),
                ('active_course_count', models.PositiveIntegerField(default=8, help_text='عدد المقررات التي سيتم عرضها في السجل', verbose_name='عدد المقررات')),
                ('active_fields', models.JSONField(default=dict, verbose_name='الحقول النشطة')),
                ('field_settings', models.JSONField(default=dict, verbose_name='إعدادات الحقول')),
                ('qr_settings', models.JSONField(default=dict, verbose_name='إعدادات QR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_templates', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'قالب سجل مقررات',
                'verbose_name_plural': 'قوالب سجلات المقررات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='قيمة الهاش')),
                ('certificate_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='هاش السجل')),
                ('transcript_data', models.JSONField(verbose_name='بيانات السجل')),
                ('email', models.EmailField(blank=True, max_length=300, null=True, verbose_name='البريد الإلكتروني')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='certificates.transcripttemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'سجل مقررات',
                'verbose_name_plural': 'سجلات المقررات',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['certificate_hash'], name='certificate_certifi_9c65e9_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['created_by', '-date'], name='certificate_created_64631c_idx'),
        ),
    ]
