# Generated by Django 4.1 on 2026-01-21
# Safe migration: Adds new fields WITHOUT removing existing ones
# This ensures existing data is preserved

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_alter_advancedcertificate_options_and_more'),
    ]

    operations = [
        # Add the new ManyToMany field for multiple roles
        # The old 'role' ForeignKey is kept for backwards compatibility
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(
                blank=True,
                related_name='user_profiles',
                to='certificates.role',
                verbose_name='الصلاحيات'
            ),
        ),
        # Add the new ManyToMany field for previous roles (for temporary role system)
        # The old 'previous_role' ForeignKey is kept for backwards compatibility
        migrations.AddField(
            model_name='userprofile',
            name='previous_roles',
            field=models.ManyToManyField(
                blank=True,
                related_name='previous_user_profiles',
                to='certificates.role',
                verbose_name='الصلاحيات السابقة'
            ),
        ),
    ]
