# Generated by Django 4.1 on 2026-01-21
# Data migration: Copies existing role data to new roles ManyToMany field
# This ensures ALL existing users keep their roles

from django.db import migrations


def migrate_roles_forward(apps, schema_editor):
    """
    Copy existing single role to the new multi-role field.
    This ensures no user loses their existing role.
    """
    UserProfile = apps.get_model('certificates', 'UserProfile')
    
    # Get all profiles that have a role assigned
    profiles_with_role = UserProfile.objects.filter(role__isnull=False)
    
    migrated_count = 0
    for profile in profiles_with_role:
        # Add the existing role to the new roles ManyToMany field
        profile.roles.add(profile.role)
        migrated_count += 1
    
    # Also migrate previous_role to previous_roles if exists
    profiles_with_previous_role = UserProfile.objects.filter(previous_role__isnull=False)
    
    for profile in profiles_with_previous_role:
        profile.previous_roles.add(profile.previous_role)
    
    print(f"Successfully migrated {migrated_count} user profiles to multi-role system")


def migrate_roles_backward(apps, schema_editor):
    """
    Reverse migration: Copy first role from roles back to role field.
    This allows safe rollback if needed.
    """
    UserProfile = apps.get_model('certificates', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        # Get the first role from the ManyToMany field
        first_role = profile.roles.first()
        if first_role:
            profile.role = first_role
            profile.save()
        
        # Also handle previous_roles
        first_previous_role = profile.previous_roles.first()
        if first_previous_role:
            profile.previous_role = first_previous_role
            profile.save()
    
    print("Successfully rolled back to single-role system")


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_add_multi_role_support'),
    ]

    operations = [
        migrations.RunPython(
            migrate_roles_forward,
            migrate_roles_backward,  # Allows safe rollback
        ),
    ]
